### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Notlucky101** [theomenden/TheOmenDen.Prefabricated#15]
### Minecraft Version

1.20.1

### Mod Version

 5.2.0

### Details

Prefabricated (prefabricated), Version: 5.2.0a t TRANSFORMER/prefabricated@5.2.0/com.theomenden.prefabricated.Utils.WrapString(Utils.java:37)

BullDozer

java.lang.NoClassDefFoundError: org/apache/commons/text/WordUtils
	at com.theomenden.prefabricated.Utils.WrapString(Utils.java:37) ~[prefabricated-5.2.0_mapped_srg_1.20.1.jar%231395!/:?] {re:classloading}
	at com.theomenden.prefabricated.Utils.WrapStringToLiterals(Utils.java:61) ~[prefabricated-5.2.0_mapped_srg_1.20.1.jar%231395!/:?] {re:classloading}
	at com.theomenden.prefabricated.Utils.WrapStringToLiterals(Utils.java:47) ~[prefabricated-5.2.0_mapped_srg_1.20.1.jar%231395!/:?] {re:classloading}
	at com.theomenden.prefabricated.structures.items.ItemBulldozer.m_7373_(ItemBulldozer.java:84) ~[prefabricated-5.2.0_mapped_srg_1.20.1.jar%231395!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:631) ~[client-1.20.1-20230612.114412-srg.jar%23826!/:?] {re:mixin,xf:fml:forge:itemstack,pl:connector_pre_launch:A,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin from mod apotheosis,pl:mixin:APP:connectormod.mixins.json:item.ItemStackMixin from mod connectormod,pl:mixin:APP:mixins.hammerlib.json:ItemStackMixin from mod hammerlib,pl:mixin:APP:useitemonblockevent.mixins.json:ItemStackMixin from mod useitemonblockevent,pl:mixin:APP:attributeslib.mixins.json:ItemStackMixin from mod attributeslib,pl:mixin:APP:tombstone.mixins.json:ItemStackMixin from mod tombstone,pl:mixin:APP:mixins.hammermultipart.json:ItemStackMixin from mod hammermultipart,pl:mixin:APP:fabric-item-api-v1.mixins.json:ItemStackMixin from mod fabric_item_api_v1,pl:mixin:APP:placebo.mixins.json:ItemStackMixin from mod placebo,pl:mixin:APP:mixins.irons_spellbooks.json:ItemStackMixin from mod irons_spellbooks,pl:mixin:APP:puzzlesapi.common.mixins.json:iteminteractions.ItemStackMixin from mod puzzlesapi,pl:mixin:APP:bettercombat.mixins.json:ItemStackMixin from mod bettercombat,pl:mixin:APP:tetra.mixins.json:ItemStackMixin from mod tetra,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin from mod itemfilters,pl:mixin:APP:quark.mixins.json:ItemStackMixin from mod quark,pl:mixin:APP:connectormod.mixins.json:item.LateItemStackMixin from mod connectormod,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.client.gui.screens.Screen.m_280152_(Screen.java:246) ~[client-1.20.1-20230612.114412-srg.jar%23826!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-screen-api-v1.mixins.json:ScreenMixin from mod fabric_screen_api_v1,pl:mixin:APP:yungsmenutweaks.mixins.json:ScreenMixin from mod yungsmenutweaks,pl:mixin:APP:konkrete.mixin.json:IMixinScreen from mod konkrete,pl:mixin:APP:balm.mixins.json:ScreenAccessor from mod balm,pl:mixin:APP:fabric-screen-api-v1.mixins.json:ScreenAccessor from mod fabric_screen_api_v1,pl:mixin:APP:controlling.mixins.json:AccessScreen from mod controlling,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen from mod patchouli,pl:mixin:APP:configured.common.mixins.json:client.ScreenMixin from mod configured,pl:mixin:APP:quark.mixins.json:client.ScreenMixin from mod quark,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_280553_(AbstractContainerScreen.java:169) ~[client-1.20.1-20230612.114412-srg.jar%23826!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apotheosis.mixins.json:client.AbstractContainerScreenMixin from mod apotheosis,pl:mixin:APP:mixins.litematica.json:IMixinHandledScreen from mod litematica,pl:mixin:APP:mixins.litematica.json:MixinHandledScreen from mod litematica,pl:mixin:APP:attributeslib.mixins.json:client.AbstractContainerScreenMixin from mod attributeslib,pl:mixin:APP:sleep-rework-common.mixins.json:client.AbstractContainerScreenMixin from mod sleeprework,pl:mixin:APP:adastra-common.mixins.json:client.AbstractContainerScreenMixin from mod ad_astra,pl:mixin:APP:findme-common.mixins.json:MixinSlotRenderer from mod findme,pl:mixin:APP:balm.mixins.json:AbstractContainerScreenAccessor from mod balm,pl:mixin:APP:puzzlesapi.common.mixins.json:iteminteractions.client.AbstractContainerScreenMixin from mod puzzlesapi,pl:mixin:APP:puzzlesapi.common.mixins.json:iteminteractions.client.accessor.AbstractContainerScreenAccessor from mod puzzlesapi,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor from mod mousetweaks,pl:mixin:APP:mixins.malilib.json:MixinHandledScreen from mod malilib,pl:mixin:APP:inventoryessentials.mixins.json:AbstractContainerScreenAccessor from mod inventoryessentials,pl:mixin:APP:controllable.common.mixins.json:client.ContainerScreenMixin from mod controllable,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin from mod quark,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_280072_(AbstractContainerScreen.java:163) ~[client-1.20.1-20230612.114412-srg.jar%23826!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:apotheosis.mixins.json:client.AbstractContainerScreenMixin from mod apotheosis,pl:mixin:APP:mixins.litematica.json:IMixinHandledScreen from mod litematica,pl:mixin:APP:mixins.litematica.json:MixinHandledScreen from mod litematica,pl:mixin:APP:attributeslib.mixins.json:client.AbstractContainerScreenMixin from mod attributeslib,pl:mixin:APP:sleep-rework-common.mixins.json:client.AbstractContainerScreenMixin from mod sleeprework,pl:mixin:APP:adastra-common.mixins.json:client.AbstractContainerScreenMixin from mod ad_astra,pl:mixin:APP:findme-common.mixins.json:MixinSlotRenderer from mod findme,pl:mixin:APP:balm.mixins.json:AbstractContainerScreenAccessor from mod balm,pl:mixin:APP:puzzlesapi.common.mixins.json:iteminteractions.client.AbstractContainerScreenMixin from mod puzzlesapi,pl:mixin:APP:puzzlesapi.common.mixins.json:iteminteractions.client.accessor.AbstractContainerScreenAccessor from mod puzzlesapi,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor from mod mousetweaks,pl:mixin:APP:mixins.malilib.json:MixinHandledScreen from mod malilib,pl:mixin:APP:inventoryessentials.mixins.json:AbstractContainerScreenAccessor from mod inventoryessentials,pl:mixin:APP:controllable.common.mixins.json:client.ContainerScreenMixin from mod controllable,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin from mod quark,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at com.refinedmods.refinedstorage.screen.BaseScreen.m_88315_(BaseScreen.java:121) ~[refinedstorage-1.12.4.jar%23749!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at com.refinedmods.refinedstorage.screen.grid.GridScreen.m_88315_(GridScreen.java:430) ~[refinedstorage-1.12.4.jar%23749!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23826!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-screen-api-v1.mixins.json:ScreenMixin from mod fabric_screen_api_v1,pl:mixin:APP:yungsmenutweaks.mixins.json:ScreenMixin from mod yungsmenutweaks,pl:mixin:APP:konkrete.mixin.json:IMixinScreen from mod konkrete,pl:mixin:APP:balm.mixins.json:ScreenAccessor from mod balm,pl:mixin:APP:fabric-screen-api-v1.mixins.json:ScreenAccessor from mod fabric_screen_api_v1,pl:mixin:APP:controlling.mixins.json:AccessScreen from mod controlling,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen from mod patchouli,pl:mixin:APP:configured.common.mixins.json:client.ScreenMixin from mod configured,pl:mixin:APP:quark.mixins.json:client.ScreenMixin from mod quark,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:427) ~[forge-1.20.1-47.2.17-universal.jar%23831!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:420) ~[forge-1.20.1-47.2.17-universal.jar%23831!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23826!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight-common.mixins.json:GameRendererMixin from mod moonlight,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing from mod oculus,pl:mixin:APP:tombstone.mixins.json:GameRendererMixin from mod tombstone,pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer from mod immediatelyfast,pl:mixin:APP:embeddiumplus.mixin.json:darkness.GameRendererMixin from mod embeddiumplus,pl:mixin:APP:mixins.artifacts.common.json:item.wearable.nightvisiongoggles.client.GameRendererMixin from mod artifacts,pl:mixin:APP:flickerfix.mixins.json:MixinGameRenderer from mod flickerfix,pl:mixin:APP:forcecraft.mixins.json:GameRendererMixin from mod forcecraft,pl:mixin:APP:prefabricated.mixins.json:ClientWorldMixin from mod prefabricated,pl:mixin:APP:fastload.mixins.json:client.GameRendererMixin from mod fastload,pl:mixin:APP:wi-zoom.mixins.json:GameRendererMixin from mod wi_zoom,pl:mixin:APP:zeta_forge.mixins.json:client.GameRenderMixin from mod zeta,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer from mod embeddium_extra,pl:mixin:APP:immersive_aircraft.mixins.json:client.GameRendererMixin from mod immersive_aircraft,pl:mixin:APP:controllable.common.mixins.json:client.GameRendererMixin from mod controllable,pl:mixin:APP:controllable.mixins.json:client.ForgeGameRendererMixin from mod controllable,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor from mod create,pl:mixin:APP:create.mixins.json:client.GameRendererMixin from mod create,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod embeddium,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat from mod oculus,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23826!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23826!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37) ~[notenoughcrashes-4.4.7+1.20.1-forge.jar%23724!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.Minecraft.modify$egj000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(Minecraft.java:18511) ~[client-1.20.1-20230612.114412-srg.jar%23826!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:738) ~[client-1.20.1-20230612.114412-srg.jar%23826!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37) ~[notenoughcrashes-4.4.7+1.20.1-forge.jar%23724!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.Minecraft.modify$egj000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(Minecraft.java:18511) ~[client-1.20.1-20230612.114412-srg.jar%23826!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:738) ~[client-1.20.1-20230612.114412-srg.jar%23826!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-1.20.1-47.2.17.jar:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin from mod flywheel,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin from mod smoothboot,pl:mixin:APP:notenoughcrashes.forge.mixins.json:client.MixinMain from mod notenoughcrashes,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.ClassNotFoundException: org.apache.commons.text.WordUtils

**Comment by Notlucky101** [comment]
check this out....https://www.youtube.com/watch?v=pM4a9wTn3ME
that is how I use some fabric mods with forge..and it works fantastic....

**Comment by Notlucky101** [comment]
still only the bulldozer is the problem..I have checked other people's
comments and there are some issues...
